# 端口
server:
  port: 9000
spring:
  # Redis配置 （SSO模式一和模式二使用Redis来同步会话）
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 124.221.112.135
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456

forest:
  # 关闭 forest 请求日志打印
  log-enabled: false
